Add contribution guidance for Tools page
best-practice-and-impact/qa-of-code-guidance pull request #153
Opened 2023-05-31 15:56 UTC by foster999

Aiming to get more user input on tools that are useful for reproducible analysis. Adding clear guidance on how to contribute to this page.

2023-06-05 11:24 UTC, rowanhemsi requested changes
A couple of comments but in general this looks like a good update

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
> +or [contacting us by email](mailto:ASAP@ons.gov.uk?subject=Duck%20Book%20Tools)
Missing full stop after link

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
> +Please include a link and brief description when requesting a new tool to be added.
Do we want an issue template for tool requests?

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
> +* [a11tables (R only)](https://co-analysis.github.io/a11ytables/index.html) * - creating reproducible, accessible spreadsheets
Missing "y" in a11ytables

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
> +* [Rgovcookiecutter (R)](https://github.com/best-practice-and-impact/Rgovcookiecutter) * - template project for reproducible analysis
Does Rgovcookiecutter exist yet?

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
> +* [twine](https://pypi.org/project/twine/) - utility for publishing Python packages to [the Python Package Index PyPI](https://pypi.org/)
Could add poetry here or in dependency management

2023-06-05 11:24 UTC, rowanhemsi commented on book/tools.md
>  * [Travis](https://travis-ci.org/)
Is Travis still recommended?

2023-06-05 11:24 UTC, rowanhemsi commented on README.md
>  Once forked, you should clone the fork repository to get a copy of the book. Then install it's Python dependencies like so:
its not it's

2023-06-09 16:49 UTC, rowanhemsi commented on book/tools.md
> +Please include a link and brief description when requesting a new tool to be added.
Issue added #155

2023-06-09 16:59 UTC, rowanhemsi commented on book/tools.md
> +Those developed or contributed to within government are marked with an asterisk (*).
Not all screen readers will read out `*`, so this should be changed for accessibility reasons

2023-06-09 17:14 UTC, rowanhemsi commented
Do we need to add a disclaimer saying that whilst we believe these tools are useful, we have not comprehensively quality assured or security checked them all and are not liable should any issues arise

2023-06-09 17:14 UTC, rowanhemsi commented on book/tools.md
> +* [twine](https://pypi.org/project/twine/) - utility for publishing Python packages to [the Python Package Index PyPI](https://pypi.org/)
Added to issue #155

2023-06-09 17:15 UTC, rowanhemsi commented on book/tools.md
>  * [Travis](https://travis-ci.org/)
Added to issue #156

2023-06-09 17:15 UTC, rowanhemsi commented on book/tools.md
> +* [Rgovcookiecutter (R)](https://github.com/best-practice-and-impact/Rgovcookiecutter) * - template project for reproducible analysis
Added to issue #156

2023-06-09 17:29 UTC, rowanhemsi commented on book/tools.md
> +Those developed or contributed to within government are marked with an asterisk (*).
Asterisk `*` replaced with `(gov)`, which should be more accessible and explicit. Feel free to change if you have an alternative suggestions

2023-06-13 11:13 UTC, robertswh approved these changes
Reviewed disclaimer wording on using the tools.

2023-06-13 11:16 UTC, rowanhemsi approved these changes
Changes requested have been implemented or an issue created to discuss. Happy for this to now be merged

2023-06-13 11:19 UTC, merged