Update glossary
best-practice-and-impact/qa-of-code-guidance pull request #186
Opened 2024-05-23 15:08 UTC by gisellerosetta

Have changed some of the suggested definitions from #173; also included 'interactive running', 'procedural running' and 'attribute' as these are used in other definitions.

Added dual running as understood in the RAP context in #168.

Actioned the suggestions on #185.

2024-06-10 09:58 UTC, sarahcollyer requested changes
Looking good! A couple of really minor and easy-to-fix things; once these are done happy for this to be merged.

- 'Code interpreter' needs to be bold 
- Can we capitalise all words in GCP, AWS and the Azure after Microsoft in the Cloud computing description? So it reads Google Cloud Platform instead of Google cloud platform.

Thanks! 😸

2024-06-10 10:17 UTC, giro090 commented
Thanks Sarah - I'll also investigate more why the CI is failing

2024-06-17 10:46 UTC, giro090 commented
CI was failing because I deleted a subtitle, which lead to style warnings about header levels that we then don't allow for in the workload build command. Thanks @danmilne1 for the spot.

2024-07-03 11:27 UTC, sarahcollyer approved these changes

2024-07-03 11:32 UTC, merged