Update config and accessibility points on checklists
best-practice-and-impact/qa-of-code-guidance pull request #99
Opened 2022-12-20 13:37 UTC by foster999

- Clarify that configuration files should be separate files above lower checklist
- Add output accessibility to all levels

2022-12-21 13:35 UTC, joe9perry7 approved these changes

2022-12-21 13:46 UTC, joshlynchONS approved these changes
Everything looks good to me.

2023-02-07 13:07 UTC, RuSnook requested changes
couple of minor grammar updates and 1 suggestion

2023-02-07 13:07 UTC, RuSnook commented on book/checklist_lower.md
> +- Published outputs meets [accessibility regulations](https://analysisfunction.civilservice.gov.uk/area_of_work/accessibility/).
verb/noun don't match: 'outputs meet' or 'output meets'

2023-02-07 13:07 UTC, RuSnook commented on book/checklist_moderate.md
> +- Configuration is stored in a dedicated configuration file, outside of the code.
Think this sounds nicer but what's there is fine. If you choose to update then will need updating in all instances.
```suggestion
- Configuration is stored in a dedicated configuration file, separate to the code.
```

2023-02-07 13:07 UTC, RuSnook commented on book/checklist_higher.md
> +- Published outputs meets [accessibility regulations](https://analysisfunction.civilservice.gov.uk/area_of_work/accessibility/).
see comment on Lower checklist

2023-02-07 13:07 UTC, RuSnook commented on book/checklist_moderate.md
> +- Published outputs meets [accessibility regulations](https://analysisfunction.civilservice.gov.uk/area_of_work/accessibility/).
see comment on lower checklist

2023-02-16 10:00 UTC, foster999 commented on book/checklist_moderate.md
> +- Configuration is stored in a dedicated configuration file, outside of the code.
Implemented this change on moderate and higher

2023-02-16 10:03 UTC, foster999 commented on book/checklist_lower.md
> +- Published outputs meets [accessibility regulations](https://analysisfunction.civilservice.gov.uk/area_of_work/accessibility/).
changed across all checklists

2023-02-16 10:04 UTC, foster999 commented
Thanks @RuSnook, I've updated those bits. Hopefully this looks alright now?

2023-02-16 10:22 UTC, RuSnook approved these changes
looks good

2023-02-16 10:23 UTC, merged